### ISSUE TITLE
Addon prints before Glass is loaded are lost.

### ISSUE THREAD

**Issue by Grimonja** [mixxorz/Glass#110]
**Describe the bug**
As title states. This is quite annoying developing with Glass loaded if you have some prints in Init phase.

**Additional context (optional)**
This can fixed by getting current messages from "DEFAULT_CHAT_FRAME" (GetNumMessages,GetMessageInfo) and adding it to Glass display at Init.

**Comment by mixxorz** [comment]
Thanks for reporting this! This is a known issue but apparently I haven't opened a ticket for it yet.

A bit unrelated, but when developing Glass, I don't use the main chatframe for debug messages. Instead I use [ViragDevTool](https://github.com/varren/ViragDevTool). It's a life saver.

**Comment by mixxorz** [comment]
Closed by #116
