### ISSUE TITLE
Chat disappears after X messages are displayed

### ISSUE THREAD

**Issue by Grimonja** [mixxorz/Glass#114]
**Describe the bug**
At one point chat completely disappears and no messages are displayed.

**To Reproduce**
1. /w Yourself
2. Spam a bit
3. ??
4. Broken 

**Does the Glass work if you disable all other addons?**
No

**Screenshots**
How it looks after it breaks
https://dl.dropboxusercontent.com/s/tghgbjbsduqlvb6/TBW1iZGV9V.mp4

**Comment by mixxorz** [comment]
Hey. I can't seem to reproduce this issue at all...

Does this still happen for you?

**Comment by Grimonja** [comment]
I cant replicate it anymore. But this might have been the cause.
https://github.com/Stanzilla/WoWUIBugs/issues/40

**Comment by mixxorz** [comment]
Cool! I'll close this for now. Not seeing any other reports about it and I'm also not experiencing this.
