### ISSUE TITLE
Cyrillic chars not working

### ISSUE THREAD

**Issue by anahka2309** [mixxorz/Glass#120]
In the EU we are grouped in with the Russian servers. Default UI and Prat support the Cyrillic alphabet. Glass doesn't and just displays questionmarks. 

See https://imgur.com/a/udboDsZ for example.

**Comment by mixxorz** [comment]
Thanks for the report!

This is usually a font issue... Are you using a font that's compatible with Cyrillic characters? I'm using Friz Quadrata TT (default WoW font) and they display fine.

**Comment by anahka2309** [comment]
That's a good point, will check. Thanks!

**Comment by anahka2309** [comment]
I switched to another font and that works. Friz Quadrata TT doesn't work though :)

**Comment by mixxorz** [comment]
Strange! Might differences in wow client locales or something. But I'm glad you found a working font!

Closing this issue now.

**Comment by goldpaw** [comment]
Just want to add for the tinkerers out there that the Cyrillic version of Friz Quadrata has its own path: 
**Fonts\FRIZQT___CYR.TTF**
