### ISSUE TITLE
After a /reload or logging in for the first time, when opening the chat to write, while using Prat, the edit box closes immediately

### ISSUE THREAD

**Issue by Shirofune** [mixxorz/Glass#121]
**Describe the bug**

Every single time I log in, for the first time, and hit Enter to start typing, the edit box closes immediately after. It only happens the first time, after that, the chat works perfectly fine.

Same issue happens when doing a UI reload through /reload or similar commands.

**To Reproduce**

1. Log in / reload UI
2. Hit Enter to open the Edit Box
3. The Edit Box immediately closes

**Expected behavior**

The Edit Box should remain opened until Enter is hit again

**Does the Glass work if you disable all other addons?**

The issue is fixed when disabling Prat, but I though Glass was compatible with this addon.

**Video**

https://www.youtube.com/watch?v=9j_ku9oU0s4

I added a video to show the bug. Slow it down as it happens very fast between 00:10 and 00:11

**Comment by mixxorz** [comment]
Thank you for the report!

Just to make sure, is Prat's EditBox module disabled?

**Comment by Shirofune** [comment]
It wasn't :).

Disabling it fixes the issue. 

I guess this was known for you already. Sorry if you already knew about this, and thanks for the fix

**Comment by mixxorz** [comment]
No worries!

I think it's not _feasibly_ possible for two addons to modify the same UI element unfortunately. The best I can do is to add in functionality that Prat's EditBox module provides to Glass itself. Those can be tracked in separate issues so I'll close this for now.
