### ISSUE TITLE
Show the whole history that can be visible when you scroll the mouse wheel up just 1 tick

### ISSUE THREAD

**Issue by fkrisi11** [mixxorz/Glass#61]
The default chat frame has this feature. If I was away for a while, I just usually scroll up the chat very very slightly (1 tick as mentioned in the title), and the whole history that can fit in the chat frame, shows up.
This would be a nice option to have, even if it wouldn't be a feature by default.

**Comment by mixxorz** [comment]
Not sure I'm understanding this correctly, but Glass already does this. When you scroll up, all chat messages that fit within the window are shown.

**Comment by fkrisi11** [comment]
Scrolling didn't work properly for me, so I couldn't tell that this was a feature. Sorry about this.
