### ISSUE TITLE
No chat input history

### ISSUE THREAD

**Issue by paroyer** [mixxorz/Glass#66]
**Describe the bug**
Just realise you couldn't click the up/down key to cycle through the last input message/command

**To Reproduce**
Enter a command for ex /help
Then press enter and then the up arrow nothing get copied

**Expected behavior**
Normally when you press enter then the up arrow it would automaticly copy the last entry, here /help

**Comment by mixxorz** [comment]
I haven't gotten down to the bottom of this yet, but I found if you hit Alt + Up/Down arrow, it will cycle. I'm not sure if this is a Prat feature or something Blizzard have added.

**Comment by paroyer** [comment]
Amazing that you realise Alt was working, it's barelly an issue now

**Comment by mixxorz** [comment]
Will still need a clear explanation of why this is.

1. Does Up/Down arrow using default Blizzard chat cycle the history? Or is it Alt + Up/Down arrow
2. I vaguely recall Prat having a setting for whether you need to Alt + Up/Down or just Up/Down arrow.

**Comment by eTzmNcbkrng** [comment]
Default UI requires pressing Alt to scroll through previously sent messages. Many Addons remove the requirement to hold Alt.

**Comment by TheSumm** [comment]
Looks like `EditBox:SetAltArrowKeyMode(enable)` might help here.
Unfortunately, it seems to be broken and only enables Left / Right navigation, Up / Down still requires the Alt key.

**Comment by mixxorz** [comment]
Thanks for the report all. I've opened #96 specifically for this new feature so I'm closing this now!
