### ISSUE TITLE
Entering Chat not showing while typing

### ISSUE THREAD

**Issue by Rolend7** [mixxorz/Glass#68]
When I am trying to type the input window is hidden. 

**To Reproduce**
1. Hit enter
2. Chat window should show with text that user is inputting
3. Not showing, but if you type something the text will show in chat

**Expected behavior**
Text should show while you are typing it. 

**Does the Glass work if you disable all other addons?**
No.

**Comment by mixxorz** [comment]
Can you try to check that your chat style is on "Classic"? Interface -> Social -> Chat style. Options are IM style and Classic. Not sure if this is it but it's an idea anyway.

**Comment by Rolend7** [comment]
Hi thank you for responding.

I checked both and tried it each way with no luck. I’ve installed it on the
beta and it works well there. It’s just on retail where I’m having issues

**Comment by Rolend7** [comment]
Mixx,

Sorry for the spam. I figured it out. SUI was causing an issue with it.

I disabled the chat functionality of that addon  and it works perfect now.
Thank you for the work you do with the add on.

**Comment by mixxorz** [comment]
Aha. No, this is useful info. Thanks! I'll add this to the README so people are aware they need to disable the chat module for SUI.

**Comment by mjrmyke** [comment]
I, too, am having this issue without SUI installed. The issue persists even when all other addons are disabled. Likely a permanent setting from another mod as it works on a level 1 character with no addons enabled except for glass.
