### ISSUE TITLE
Whisper and Battle.net chat

### ISSUE THREAD

**Issue by Dentrium** [mixxorz/Glass#69]
When right clicking a whisp chat to Move to a Whisper Window this is what happens. 
chat gets bugged and duplicated in general chat frame.

![Untitled](https://user-images.githubusercontent.com/70178439/91105116-9c70ee00-e645-11ea-9f0c-23119abb077d.png)

**Comment by Dentrium** [comment]
also happens the same when you try to move a Battle tag chat.

**Comment by mixxorz** [comment]
Thanks for the report! I'm closing this in lieu of #54.
