### ISSUE TITLE
addon is not working after the update.

### ISSUE THREAD

**Issue by 69minuteman** [mixxorz/Glass#84]
**Describe the bug**
It literally stopped working after the recent update 1.2

**To Reproduce**
1. log in to game

**Comment by mixxorz** [comment]
Hi! Are you able to provide an error log? It would really help me with debugging.

**Comment by 69minuteman** [comment]
umm, I saw you flagged spy addon as incompatible 
so I unloaded spy addon and it is working for now.

With spy addon on, Glass seems doing nothing to the chat.
chat just going back to vanilla.

**Comment by mixxorz** [comment]
I'm gonna close this in lieu of #86. Thanks for bringing this up though!
