### ISSUE TITLE
Addon incompatibility: Spy

### ISSUE THREAD

**Issue by mixxorz** [mixxorz/Glass#86]
**Describe the bug**
Spy does not work with Glass.

https://www.curseforge.com/wow/addons/spy

Possibly because Glass modifies the Combat Log.

**Comment by Lewdlordx** [comment]
I literally have no idea why it does what it does.. or why this does anything to resolve it.. but figured I should share it at least.

By simply adding **return self.db.profile** to the end of the **Core:OnInitialize()** in **init.lua** I no longer have any issue with spy on Classic. It doesn't even have to be **return self.db.profile**.. at first I had **DevTools_Dump(self.db.profile)** and it seemed to work. As long as you're some how calling the array specifically.

[https://i.imgur.com/yBqUhwo.png](As you can see in this screenshot)

[https://www.diffchecker.com/rnPKBbGd#right-2](Here's the code difference)

**Comment by Lewdlordx** [comment]
What I do know is, that minor change allows this db table to contain the missing variables.

[Before change - Missing variables](https://i.imgur.com/NwLZGlj.png)

[After change - Variables](https://i.imgur.com/slOHgBh.png)

**Comment by mixxorz** [comment]
Thanks for helping with debugging!

I've made a recent change with db, do you mind trying version 1.4.1 and see if that works?

**Comment by Lewdlordx** [comment]
From what I can tell, it works so far on Classic.

**Comment by mixxorz** [comment]
Sorry just to confirm, is it working now with Spy on Classic?

**Comment by Lewdlordx** [comment]
Yes. SpyClassic1.1.1-release is currently working along side Glass-1.4.1-classic.

**Comment by mixxorz** [comment]
That's awesome!

Basically I was doing something weird with the AceDB saved variables and I think that was having unintended consequences with Spy (but curiously, no other addon). Release 1.4.1 fixes the AceDB issue, which seems to have fixed Spy compatibility as well. Awesome!

I'll close this now. Thanks for debugging!!
