### ISSUE TITLE
LUA error when combined with Leatrix Plus

### ISSUE THREAD

**Issue by Nillx** [mixxorz/Glass#87]
Im using Leatrix Plus and decided to install Glass today. Now im getting this error:

```
1x Leatrix_Plus\Leatrix_Plus-8.3.34.lua:5080: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
[string "=[C]"]: ?
[string "@Bartender4\libs\AceHook-3.0\AceHook-3.0-8.lua"]:130: in function <...eBartender4\libs\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Bartender4\libs\AceHook-3.0\AceHook-3.0-8.lua"]:367: in function `HookScript'
[string "@Leatrix_Plus\Leatrix_Plus-8.3.34.lua"]:5080: in function `?'
[string "@Leatrix_Plus\Leatrix_Plus-8.3.34.lua"]:8408: in function <Leatrix_Plus\Leatrix_Plus.lua:7976>

Locals:
(*temporary) = "Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string"
```

I reported to Leatrix but im not sure which addon is actually causing it.

**Comment by 69minuteman** [comment]
Spy, Details and now Leatrix plus... I am using them all D:
I am using old versions for now. 👍

**Comment by mixxorz** [comment]
It's strange because that error log doesn't show any references to Glass. Are you sure it's Glass causing the issues and not Leatrix Plus itself?

Also, I'm also using Details and have not encountered issues so far.

**Comment by Nillx** [comment]
Im not getting that error when im using other chat addons like Prat or BasicChatMods. Only when Glass is enabled. 

Firstly i reported this issue to Leatrix and this was his response: "From the error, it seems to be caused by 'Recent chat window' ('Chat').  However, I'm not seeing this error."

I think i found what was causing the issue. For some reason i was unable to turn off this 4 settings in Leatrix plus when Glass was enabled. 
![image](https://user-images.githubusercontent.com/34476875/92089552-fbb5c780-edd6-11ea-820a-70f9d3b81f7b.png)

First i disabled Glass
Then i was able to turn off this options
After that i enabled Glass again with LTP
Im no longer getting that error, even after moving the chat around and reloading.

**Comment by mixxorz** [comment]
Nice! Thanks for working to debug that. I'll make sure to note this on the README and the CurseForge page for other users.

**Comment by Nillx** [comment]
"Use easy resizing" option is also causing issues. Dont use it.

**Comment by mixxorz** [comment]
I've noted this down on the README and the CurseForge page so I think we're good here!
