### ISSUE TITLE
A few QOL suggestions

### ISSUE THREAD

**Issue by Nillx** [mixxorz/Glass#88]
Thanks for making this addon, i really like how smooth it is. Got a few QoL suggestions that will make it even better in my opinion.

1. My chat is in the bottom left corner and i would love the have the EditBox on top of the chat instead in the bottom. I already found a way to do that by editing the lua but would be nice to have a quick option for it. 

2. There is no way to change the font size of the text inside the Edit Box. I set the font size to 14 but the chat buttons (like General, Log etc) and the edit box are stuck at font size 11-12 (pretty hard to read from a distance). With some manual editing i did found a way to change the font size of EditBox and make it bigger but a separate option for that will be much cleaner.

3. Can you let us change the space between chat messages? I think they are too far apart with the default settings.

4. Would love to have some kind of option that let us copy parts of the chat, copy/paste like. 

5. Make site links copy/paste-able.

**Comment by mixxorz** [comment]
Hey @Nillx . Thanks for this!

I would love to add all of these features! Thank you for the suggestions!

**Comment by Nillx** [comment]
Thanks for the addon :)

**Comment by mixxorz** [comment]
Release 1.5.0 adds a bunch of these things.

1. EditBox can now be pinned above the chat window
2. You can now control the edit box font size
3. You can now control font leading and line padding for the messages
4. Copy/paste chat is tracked separately here: https://github.com/mixxorz/Glass/issues/65
5. Prat's copy/paste URL feature now works with Glass.
