### ISSUE TITLE
[Classic] Icons don't move with messages until the animation is complete

### ISSUE THREAD

**Issue by Lewdlordx** [mixxorz/Glass#97]
**Describe the bug**
Icons that are displayed in chat don't move with the message when chat is active and pushing the previous messages up through animation effects. Once the animation is complete, the icons reposition correctly but not during the animation.

**To Reproduce**
1. Log into classic
2. Type a message containing a icon (I.E. {skull})
3. Type more messages which pushes the previous message up
4. See the icons not reposition until animation of the message going up finishes

**Expected behavior**
Icons (I.E. {skull}) scroll up with messages in a seamless animation.

**Does the Glass work if you disable all other addons?**
Still happens whether all addons or nothing but Glass is enabled

**Screenshots**
[https://i.imgur.com/7IGdjQ2.png](https://i.imgur.com/7IGdjQ2.png)

**Comment by mixxorz** [comment]
Hi! Thanks for the report. This is a known limitation with WoW UI's animation APIs. However, I do have a workaround cooking so hopefully this will be fixed soon!

**Comment by mixxorz** [comment]
This has been fixed with release 1.4.2.
